getdents01: Fix implicit getdents64 declaration on glibc 2.30
glibc commit b8b3d5a14e ("Linux: Move getdents64 to <dirent.h>")
moved the declaration from <unistd.h> to <dirent.h> to match
the location of the declaration in musl.

Thus we need to include both <dirent.h> and <unistd.h> for getdents64().

Using getdents64() declaration requires on both glibc and musl
_GNU_SOURCE definition, thus add it into getdents01.c

This fixes build error:
gcc -Werror=implicit-function-declaration -g -O2 -fno-strict-aliasing -pipe -Wall -W -Wold-style-definition  -I../../../../include -I../../../../include -I../../../../include/old/   -L../../../../lib  getdents01.c   -lltp -o getdents01
getdents01.c: In function 'mmain':
getdents01.c:112:11: error: implicit declaration of function 'getdents64'; did you mean 'getdents'? [-Werror=implicit-function-declaration]

Fixes: 587
Reported-by: Cyril Hrubis <chrubis@suse.cz>
Acked-by: Cyril Hrubis <chrubis@suse.cz>
Signed-off-by: Petr Vorel <pvorel@suse.cz>