lapi/capability.h: Fix build error because of undefined CAP_SYS_TIME
Details of the build log:
-------------------------------------------
In file included from settimeofday02.c:11:
settimeofday02.c:67:25: error: ‘CAP_SYS_TIME’ undeclared here (not in a function); did you mean ‘CAP_SYS_ADMIN’?
   TST_CAP(TST_CAP_DROP, CAP_SYS_TIME),
--------------------------------------------

Signed-off-by: Ronald Monthero <rmonther@redhat.com>
Reviewed-by: Xiao Yang <ice_yangxiao@163.com>
Acked-by: Yang Xu <xuyang2018.jy@cn.fujitsu.com>