syscalls/clock_gettime: Fix compilation on old distros
clock_gettime01.c:61: error: ‘CLOCK_BOOTTIME’ undeclared here (not in a function)

Fixes: fadc7eb84 ("syscalls/clock_gettime: create clock_gettime syscall tests")

Signed-off-by: Petr Vorel <pvorel@suse.cz>