openposix/20-1-buildonly: Remove test for sigstack structure
Since glibc 2.26, the __USE_XOPEN2K8 macro defined by default _POSIX_C_SOURCE = 200809L
&& _XOPEN_SOURCE = 700 in CFLAGS triggered the following compiler errors, because both
sigstack structure and bsd_signal function are only declared if __USE_XOPEN_EXTENDED is
defined and __USE_XOPEN2K8 is not defined:
-------------------------------------------------------------------------------
20-1-buildonly.c:13:8: error: invalid use of undefined type 'struct sigstack'
  sp = t.ss_sp;
...
signal_h/23-1.c:15:13: error: 'bsd_signal' undeclared (first use in this function); did you mean 'psignal'?
  dummyvar = bsd_signal;
-------------------------------------------------------------------------------

signal_h/23-1.c has been removed by commit d256a97, so just remove obsolete
signal_h/20-1-buildonly.c as well.

References:
https://sourceware.org/git/?p=glibc.git;a=commit;h=666c0c5efa6db73632a6894bf028fef9f3b60d71
https://sourceware.org/git/?p=glibc.git;a=commit;h=4c3992fc459322a7c712700ba3244fcb125163d7

Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>
Reviewed-by: Enji Cooper <yaneurabeya@gmail.com>