syscalls/syncfs: Fix compilation on older distros
gcc -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall -W -Wold-style-definition -D_FORTIFY_SOURCE=2 -I../../../../include -I../../../../include -I../../../../include/old/   -L../../../../lib  syncfs01.c   -lltp -o syncfs01
In file included from syncfs01.c:19:
../../../../include/lapi/syncfs.h: In function ‘syncfs’:
../../../../include/lapi/syncfs.h:17: warning: implicit declaration of function ‘syscall’
../../../../include/lapi/syncfs.h:17: warning: implicit declaration of function ‘tst_brk’
../../../../include/lapi/syncfs.h:17: error: ‘TCONF’ undeclared (first use in this function)
../../../../include/lapi/syncfs.h:17: error: (Each undeclared identifier is reported only once
../../../../include/lapi/syncfs.h:17: error: for each function it appears in.)
In file included from ../../../../include/tst_test.h:25,
                 from syncfs01.c:20:
/usr/include/unistd.h: At top level:
/usr/include/unistd.h:1068: error: conflicting types for ‘syscall’
../../../../include/lapi/syncfs.h:17: note: previous implicit declaration of ‘syscall’ was here
make: *** [syncfs01] Error 1

Fixes: b88b3785d ("syscalls: add syncfs() sync device test-case")

Signed-off-by: Petr Vorel <pvorel@suse.cz>