lib: Build tst_path_has_mnt_flags.c also on Android
This fixes android build, as since 7313a879d7 is needed in library:
tst_test.c:737: error: undefined reference to 'tst_path_has_mnt_flags_'

Fixes: 7313a879d7 ("lib/tst_test.c: Add .needs_devfs flag")

Acked-by: Jan Stancek <jstancek@redhat.com>
Signed-off-by: Petr Vorel <petr.vorel@gmail.com>